# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 86038aee58cf1aff11cdb3e4e625ddbe79112f66a2d721362b7db1e50c6b6b5dde381a1a13d21b105aea9553515eae5154f935d4f51cdd9a09a61af979213dc8

test:
  secret_key_base: 8c24db0fc30d319bba39332976f4b30504e9f620a6ffeb1f6d1c13da6a4af4cfe6a73f9e881b7a0865612ac936fd7ca91b178f1acc3245fe6ebb262015525c3d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
